# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/system_vga/system_vga.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_vga || ORIG_REF_NAME==system_vga} -quiet] -quiet

# IP: bd/system_vga/ip/system_vga_vga_ip_0_2/system_vga_vga_ip_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_vga_vga_ip_0_2 || ORIG_REF_NAME==system_vga_vga_ip_0_2} -quiet] -quiet

# IP: bd/system_vga/ip/system_vga_processing_system7_0_1/system_vga_processing_system7_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_vga_processing_system7_0_1 || ORIG_REF_NAME==system_vga_processing_system7_0_1} -quiet] -quiet

# IP: bd/system_vga/ip/system_vga_ps7_0_axi_periph_1/system_vga_ps7_0_axi_periph_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_vga_ps7_0_axi_periph_1 || ORIG_REF_NAME==system_vga_ps7_0_axi_periph_1} -quiet] -quiet

# IP: bd/system_vga/ip/system_vga_rst_ps7_0_100M_1/system_vga_rst_ps7_0_100M_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_vga_rst_ps7_0_100M_1 || ORIG_REF_NAME==system_vga_rst_ps7_0_100M_1} -quiet] -quiet

# IP: bd/system_vga/ip/system_vga_ila_0_0/system_vga_ila_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_vga_ila_0_0 || ORIG_REF_NAME==system_vga_ila_0_0} -quiet] -quiet

# IP: bd/system_vga/ip/system_vga_auto_pc_0/system_vga_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_vga_auto_pc_0 || ORIG_REF_NAME==system_vga_auto_pc_0} -quiet] -quiet

# XDC: bd/system_vga/system_vga_ooc.xdc
